.PHONY: adapterkit
adapterkit:
	adapterkit generate -mod github.com/pmg-tools/adapterkit-module-swissknife -tpl ../../../templates/aws/lambda proto/swissknife.proto


.PHONY: clean
clean:
	rm -rf pkg/*_gen
